// Shell-only strings (companion band + status strip). v2.* namespace.
export const shellStrings = {
  en: {
    'v2.nav.mochi.line':      'ready with today’s finds',
    'v2.nav.peppercorn.line': 'wondering about a few things',
    'v2.nav.saffron.line':    'watching from the window',
    'v2.nav.mochi.name':      'Mochi',
    'v2.nav.peppercorn.name': 'Peppercorn',
    'v2.nav.saffron.name':    'Saffron',
    'v2.status.line':         'Mochi is happy and full.',
    'v2.status.fresh':        '{n} things ready for you',
    'v2.status.celebrate':    'Mochi heard {venue} said yes!',
    'v2.status.celebrate.sub':'She is doing little circles about it.',
    'v2.report.link':         'Something off? Tell Peppercorn',
    'v2.report.prompt':       'Peppercorn is listening. What seemed wrong, confusing, or missing?',
    'v2.report.placeholder':  'e.g. “this gallery closed last year” or “I don’t understand this section”…',
    'v2.report.send':         'Leave it with Peppercorn',
    'v2.report.cancel':       'Never mind',
    'v2.report.thanks':       'Peppercorn wrote it down ✓',
    'v2.snav.mochi.focus':          'Today’s Focus',
    'v2.snav.mochi.board':          'Hunt Board',
    'v2.snav.saffron.overview':     'From up here',
    'v2.snav.saffron.journey':      'Journey',
    'v2.snav.saffron.field':        'Market',
    'v2.snav.saffron.peers':        'Peers',
    'v2.snav.saffron.notes':        'Field Notes',
    'v2.snav.peppercorn.wondering': 'Questions',
    'v2.snav.peppercorn.knows':     'Profile',
    'v2.snav.peppercorn.record':    'Record Book',
    'v2.snav.peppercorn.milestones':'Milestones',
  },
  zh: {
    'v2.nav.mochi.line':      '今日发现已备好',
    'v2.nav.peppercorn.line': '有几件事想问问你',
    'v2.nav.saffron.line':    '正在窗边眺望',
    'v2.nav.mochi.name':      '猫饼',
    'v2.nav.peppercorn.name': '花椒',
    'v2.nav.saffron.name':    '小红',
    'v2.status.line':         '猫饼吃得饱饱的，心情很好。',
    'v2.status.fresh':        '已为你备好 {n} 件事',
    'v2.status.celebrate':    '猫饼听说 {venue} 答应了！',
    'v2.status.celebrate.sub':'她高兴得转圈圈。',
    'v2.report.link':         '有点不对？告诉花椒',
    'v2.report.prompt':       '花椒在听。哪里看起来不对、让人困惑，或是缺了什么？',
    'v2.report.placeholder':  '比如「这家画廊去年关门了」或「这部分我看不懂」……',
    'v2.report.send':         '交给花椒',
    'v2.report.cancel':       '没事了',
    'v2.report.thanks':       '花椒记下来了 ✓',
    'v2.snav.mochi.focus':          '今日重点',
    'v2.snav.mochi.board':          '猎场',
    'v2.snav.saffron.overview':     '鸟瞰',
    'v2.snav.saffron.journey':      '路线',
    'v2.snav.saffron.field':        '市场',
    'v2.snav.saffron.peers':        '同行',
    'v2.snav.saffron.notes':        '笔记',
    'v2.snav.peppercorn.wondering': '提问',
    'v2.snav.peppercorn.knows':     '档案',
    'v2.snav.peppercorn.record':    '记录册',
    'v2.snav.peppercorn.milestones':'里程碑',
  },
  ja: {
    'v2.nav.mochi.line':      '今日の見つけものが届いています',
    'v2.nav.peppercorn.line': '聞きたいことがあるようです',
    'v2.nav.saffron.line':    '窓辺から眺めています',
    'v2.nav.mochi.name':      'モチ',
    'v2.nav.peppercorn.name': 'ペッパーコーン',
    'v2.nav.saffron.name':    'サフラン',
    'v2.status.line':         'モチは満腹でご機嫌です。',
    'v2.status.fresh':        '{n} 件の準備ができています',
    'v2.status.celebrate':    '{venue} からよい返事が来たそうです！',
    'v2.status.celebrate.sub':'モチはうれしくてくるくる回っています。',
    'v2.report.link':         '何か変？ペッパーコーンに伝える',
    'v2.report.prompt':       'ペッパーコーンが聞いています。おかしい・わかりにくい・足りないと感じたことは？',
    'v2.report.placeholder':  '例：「このギャラリーは去年閉店した」「この部分の意味がわからない」……',
    'v2.report.send':         'ペッパーコーンに預ける',
    'v2.report.cancel':       'やっぱり大丈夫',
    'v2.report.thanks':       'ペッパーコーンが書き留めました ✓',
    'v2.snav.mochi.focus':          '今日のフォーカス',
    'v2.snav.mochi.board':          '狩り場',
    'v2.snav.saffron.overview':     '高みから',
    'v2.snav.saffron.journey':      '道のり',
    'v2.snav.saffron.field':        'マーケット',
    'v2.snav.saffron.peers':        '同世代',
    'v2.snav.saffron.notes':        'ノート',
    'v2.snav.peppercorn.wondering': '質問',
    'v2.snav.peppercorn.knows':     'プロフィール',
    'v2.snav.peppercorn.record':    '記録帳',
    'v2.snav.peppercorn.milestones':'マイルストーン',
  },
}
