// Shell-only strings (companion band + status strip). v2.* namespace.
export const shellStrings = {
  en: {
    'v2.nav.mochi.line':      'ready with today’s finds',
    'v2.nav.peppercorn.line': 'wondering about a few things',
    'v2.nav.saffron.line':    'watching from the window',
    'v2.nav.mochi.name':      'Mochi',
    'v2.nav.peppercorn.name': 'Peppercorn',
    'v2.nav.saffron.name':    'Saffron',
    'v2.status.line':         'Mochi is happy and full.',
    'v2.status.fresh':        '{n} things ready for you',
    'v2.status.celebrate':    'Mochi heard {venue} said yes!',
    'v2.status.celebrate.sub':'She is doing little circles about it.',
  },
  zh: {
    'v2.nav.mochi.line':      '今日发现已备好',
    'v2.nav.peppercorn.line': '有几件事想问问你',
    'v2.nav.saffron.line':    '正在窗边眺望',
    'v2.nav.mochi.name':      '猫饼',
    'v2.nav.peppercorn.name': '花椒',
    'v2.nav.saffron.name':    '小红',
    'v2.status.line':         '猫饼吃得饱饱的，心情很好。',
    'v2.status.fresh':        '已为你备好 {n} 件事',
    'v2.status.celebrate':    '猫饼听说 {venue} 答应了！',
    'v2.status.celebrate.sub':'她高兴得转圈圈。',
  },
  ja: {
    'v2.nav.mochi.line':      '今日の見つけものが届いています',
    'v2.nav.peppercorn.line': '聞きたいことがあるようです',
    'v2.nav.saffron.line':    '窓辺から眺めています',
    'v2.nav.mochi.name':      'モチ',
    'v2.nav.peppercorn.name': 'ペッパーコーン',
    'v2.nav.saffron.name':    'サフラン',
    'v2.status.line':         'モチは満腹でご機嫌です。',
    'v2.status.fresh':        '{n} 件の準備ができています',
    'v2.status.celebrate':    '{venue} からよい返事が来たそうです！',
    'v2.status.celebrate.sub':'モチはうれしくてくるくる回っています。',
  },
}
