"""
add_koenji_shimokitazawa_venues.py
One-shot patch: adds 12 Koenji + Shimokitazawa café/bookshop/zine venues
as Tier 1 IBM-eligible opportunities.

Run once: python scripts/patches/add_koenji_shimokitazawa_venues.py
"""
import sys
import json
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT     = Path(__file__).parent.parent.parent
OPP_PATH = ROOT / "deploy_data" / "compact_opportunities.json"

NEW_VENUES = [
    {
        "name": "B&B (Book & Beer)",
        "title": "B&B (Book & Beer)",
        "organization": "B&B",
        "category": "bookstore_gallery",
        "category_label": "Bookshop / Art Books",
        "city": "Shimokitazawa, Tokyo",
        "country": "Japan",
        "official_website": "https://bookandbeer.com/",
        "submission_page": "https://bookandbeer.com/",
        "source_url": "https://bookandbeer.com/",
        "one_sentence": "Shimokitazawa's beloved bookshop-bar that stocks art books, zines, and hosts author events — the most natural home for quiet urban watercolor work in the neighborhood.",
        "three_bullets": [
            "Consigns art books and zines with low friction — the ideal first step toward printed presence in Tokyo",
            "Cultural anchor of Shimokitazawa's creative scene; high-quality visitor profile of artists, writers, designers",
            "Events program creates natural opportunity to present work beyond simple consignment"
        ],
        "why_this_fits_short": "Warm, literary atmosphere that matches the quiet observation tone of your work — not a white-cube gallery, which is correct for where you are right now.",
        "quick_action": "Visit in person, review their current shelves, ask about consignment terms for self-published or artist books.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["shimokitazawa", "bookshop", "consignment", "zine", "artist book", "Tier1"],
        "overall_score": 7.8,
        "differentiated_score": 7.8,
        "truth_aligned_score": 7.8,
        "painting_priority_score": 8.0,
        "source_purity_score": 8.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "BONUS TRACK Shimokitazawa",
        "title": "BONUS TRACK Shimokitazawa",
        "organization": "BONUS TRACK",
        "category": "zine_shop_consignment",
        "category_label": "Zine Shop / Consignment",
        "city": "Shimokitazawa, Tokyo",
        "country": "Japan",
        "official_website": "https://bonus-track.net/",
        "submission_page": "https://bonus-track.net/",
        "source_url": "https://bonus-track.net/",
        "one_sentence": "A curated lane of indie shops in Shimokitazawa — multiple venues under one roof including bookshops, record stores, and a café, all with strong art-culture orientation.",
        "three_bullets": [
            "Several shops within BONUS TRACK stock zines and artist prints — multiple consignment targets in one visit",
            "Strong community identity with Shimokitazawa's creative scene: music, books, independent craft",
            "Opened 2020, newer audience that responds well to locally made and self-published work"
        ],
        "why_this_fits_short": "Multiple low-friction entry points in a single cultural cluster — worth one research visit to identify which shop within is the best fit.",
        "quick_action": "Walk the lane, identify the shop(s) most aligned with illustrated/watercolor work, ask about consignment.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["shimokitazawa", "collective", "zine", "consignment", "indie shops", "Tier1"],
        "overall_score": 7.4,
        "differentiated_score": 7.4,
        "truth_aligned_score": 7.4,
        "painting_priority_score": 7.5,
        "source_purity_score": 7.5,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "Mona Records",
        "title": "Mona Records",
        "organization": "Mona Records",
        "category": "zine_shop_consignment",
        "category_label": "Zine Shop / Consignment",
        "city": "Shimokitazawa, Tokyo",
        "country": "Japan",
        "official_website": "https://monarecords.com/",
        "source_url": "https://monarecords.com/",
        "one_sentence": "Shimokitazawa's independent record store with a strong art and zine culture — hosts events and has carried artist-made merchandise alongside music.",
        "three_bullets": [
            "Established indie cultural node with loyal neighborhood following",
            "Music-art crossover community: overlaps with the same audience who buys artist zines and prints",
            "Direct relationship-building with the kind of independent cultural venue that can introduce your work to a wider network"
        ],
        "why_this_fits_short": "Not a gallery, which is the right frame — your work entering circulation through music-adjacent cultural spaces is quiet, credible, and low-pressure.",
        "quick_action": "Visit in person, check if they stock zines or printed art, inquire about consignment.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["shimokitazawa", "record shop", "zine", "consignment", "indie", "Tier1"],
        "overall_score": 7.0,
        "differentiated_score": 7.0,
        "truth_aligned_score": 7.0,
        "painting_priority_score": 7.0,
        "source_purity_score": 7.5,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "medium",
        "recommendation_strength": "moderate",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "medium",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "Village Vanguard Shimokitazawa",
        "title": "Village Vanguard Shimokitazawa",
        "organization": "Village Vanguard",
        "category": "bookstore_gallery",
        "category_label": "Bookshop / Art Books",
        "city": "Shimokitazawa, Tokyo",
        "country": "Japan",
        "official_website": "https://www.village-v.co.jp/",
        "source_url": "https://www.village-v.co.jp/",
        "one_sentence": "Eclectic Japanese lifestyle/book chain with a legendary Shimokitazawa branch — known for stocking unusual printed goods, artist zines, and character merchandise alongside books.",
        "three_bullets": [
            "Chain store with genuine indie sensibility: actively sources unusual, handmade, and artist-produced items",
            "High foot traffic in Shimokitazawa's busiest shopping zone — visibility without gallery framing",
            "Consignment model for small publishers and artists is well-established"
        ],
        "why_this_fits_short": "Volume venue that can move printed work without requiring gallery-level credentials — appropriate for this career phase.",
        "quick_action": "Research their consignment process (often via local store contact) and bring a sample of work.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["shimokitazawa", "bookshop", "consignment", "zine", "lifestyle", "Tier1"],
        "overall_score": 6.8,
        "differentiated_score": 6.8,
        "truth_aligned_score": 6.8,
        "painting_priority_score": 6.8,
        "source_purity_score": 7.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "medium",
        "recommendation_strength": "moderate",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "medium",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "ERA Shimokitazawa",
        "title": "ERA Shimokitazawa",
        "organization": "ERA",
        "category": "artist_space",
        "category_label": "Artist Space / Run Space",
        "city": "Shimokitazawa, Tokyo",
        "country": "Japan",
        "source_url": "https://era.shimokitazawa.jp/",
        "official_website": "https://era.shimokitazawa.jp/",
        "one_sentence": "Alternative culture venue in Shimokitazawa — events, exhibitions, and the kind of art-music crossover space where quiet observational work can find an unexpected home.",
        "three_bullets": [
            "Shimokitazawa alternative culture institution with history of cross-genre art programming",
            "Small event capacity = intimate exhibition setting appropriate for quiet, detail-focused watercolor",
            "Community-led programming means work is evaluated on cultural fit, not institutional prestige"
        ],
        "why_this_fits_short": "Low-pressure alternative space where the work can be shown without heavyweight CV requirements.",
        "quick_action": "Check their current programming, attend an event, make contact in person.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["shimokitazawa", "alternative", "event space", "artist space", "Tier1"],
        "overall_score": 7.0,
        "differentiated_score": 7.0,
        "truth_aligned_score": 6.8,
        "painting_priority_score": 7.0,
        "source_purity_score": 7.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "medium",
        "recommendation_strength": "moderate",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "medium",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "円盤 (Enban) Koenji",
        "title": "円盤 (Enban) Koenji",
        "organization": "円盤",
        "category": "zine_shop_consignment",
        "category_label": "Zine Shop / Consignment",
        "city": "Koenji, Tokyo",
        "country": "Japan",
        "official_website": "https://enban.shop/",
        "source_url": "https://enban.shop/",
        "one_sentence": "Koenji's independent record and zine shop — one of the cultural anchors of the neighborhood's alternative scene, stocks artist-made printed work.",
        "three_bullets": [
            "Core node of Koenji's alternative/indie cultural community — high cultural credibility, low barrier to entry",
            "Actively stocks self-published zines and artist books alongside music",
            "Koenji has the densest concentration of alternative culture venues in Tokyo — one relationship here opens others"
        ],
        "why_this_fits_short": "Koenji's equivalent of Shimokitazawa's record shops — the same logic applies. Getting your work stocked here is quiet, credible, and builds local name recognition.",
        "quick_action": "Visit in person, browse their zine/printed goods section, ask about consignment process.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["koenji", "zine", "record shop", "consignment", "indie", "alternative", "Tier1"],
        "overall_score": 7.5,
        "differentiated_score": 7.5,
        "truth_aligned_score": 7.5,
        "painting_priority_score": 7.5,
        "source_purity_score": 8.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "素人の乱 (Shiroto no Ran) Koenji",
        "title": "素人の乱 (Shiroto no Ran) Koenji",
        "organization": "素人の乱",
        "category": "zine_shop_consignment",
        "category_label": "Zine Shop / Consignment",
        "city": "Koenji, Tokyo",
        "country": "Japan",
        "official_website": "https://shiroto.stores.jp/",
        "source_url": "https://shiroto.stores.jp/",
        "one_sentence": "Koenji's famous alternative junk shops and political-culture spaces — an ecosystem that overlaps heavily with zine culture and has space for subversive or quiet observational art.",
        "three_bullets": [
            "Koenji cultural institution with a decades-long history of supporting independent/alternative artists",
            "DIY ethos: work doesn't need institutional framing to belong here",
            "Overlapping social network with zine fairs, live events, and political/countercultural art"
        ],
        "why_this_fits_short": "A completely different audience from the gallery world — introduces your work to people who wouldn't normally encounter it through fine-art channels.",
        "quick_action": "Visit the shop cluster in Koenji, see whether they stock zines or printed art, make contact.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["koenji", "alternative", "DIY", "zine", "consignment", "Tier1"],
        "overall_score": 6.8,
        "differentiated_score": 6.8,
        "truth_aligned_score": 6.8,
        "painting_priority_score": 6.5,
        "source_purity_score": 7.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "medium",
        "recommendation_strength": "moderate",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "medium",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "Koenji SANAGI",
        "title": "Koenji SANAGI",
        "organization": "SANAGI",
        "category": "cafe_gallery",
        "category_label": "Café Gallery",
        "city": "Koenji, Tokyo",
        "country": "Japan",
        "source_url": "https://sanagi.koenji.jp/",
        "official_website": "https://sanagi.koenji.jp/",
        "one_sentence": "Koenji art café and event space — one of the neighborhood's key cultural meeting points for local artists, musicians, and writers.",
        "three_bullets": [
            "Consistent exhibition programming for local/emerging artists without heavy CV requirements",
            "Café setting means work is encountered in a relaxed, daily-life context rather than a formal white cube",
            "Koenji community hub — strong for local relationship-building"
        ],
        "why_this_fits_short": "Exactly the kind of low-pressure Tier 1 space that builds local recognition — the right move before approaching the more competitive Tokyo gallery scene.",
        "quick_action": "Visit during opening hours, check wall space, ask about their exhibition program and how artists apply.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["koenji", "café gallery", "exhibition", "local", "Tier1"],
        "overall_score": 7.2,
        "differentiated_score": 7.2,
        "truth_aligned_score": 7.0,
        "painting_priority_score": 7.2,
        "source_purity_score": 7.5,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "Nantoka Bar Koenji",
        "title": "Nantoka Bar Koenji",
        "organization": "Nantoka Bar",
        "category": "cafe_gallery",
        "category_label": "Café Gallery",
        "city": "Koenji, Tokyo",
        "country": "Japan",
        "source_url": "https://nantoka.bar/",
        "official_website": "https://nantoka.bar/",
        "one_sentence": "Koenji bar and cultural space known for zine events, readings, and DIY art programming — part of the neighborhood's countercultural fabric.",
        "three_bullets": [
            "Regular art and zine events, low barrier to participation or exhibition",
            "Strong relationship with Koenji's creative community — a venue where getting your work on the wall also means meeting people",
            "DIY aesthetic matches handmade/printed work well"
        ],
        "why_this_fits_short": "Informal exhibition and event space — the kind of place where showing work once leads to further introductions.",
        "quick_action": "Check their events calendar, attend something, introduce yourself.",
        "submission_strategy": "in_person_visit",
        "submission_tone": "casual_introduction",
        "tags": ["koenji", "bar", "zine events", "DIY", "cultural space", "Tier1"],
        "overall_score": 6.6,
        "differentiated_score": 6.6,
        "truth_aligned_score": 6.5,
        "painting_priority_score": 6.5,
        "source_purity_score": 7.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "medium",
        "recommendation_strength": "moderate",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "medium",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "COW BOOKS Nakameguro",
        "title": "COW BOOKS Nakameguro",
        "organization": "COW BOOKS",
        "category": "bookstore_gallery",
        "category_label": "Bookshop / Art Books",
        "city": "Nakameguro, Tokyo",
        "country": "Japan",
        "official_website": "https://www.cowbooks.jp/",
        "source_url": "https://www.cowbooks.jp/",
        "one_sentence": "One of Tokyo's best independent bookshops — curated secondhand and new books with strong art, photography, and design focus, and a history of stocking artist-made publications.",
        "three_bullets": [
            "Highly curated selection means getting your work stocked is genuinely meaningful — they choose carefully",
            "Adjacent audience to UTRECHT but more residential/quieter — different buyer profile worth reaching",
            "Nakameguro shop has canal-side foot traffic with high cultural consumption"
        ],
        "why_this_fits_short": "COW BOOKS has the curatorial sensibility to recognize quiet, serious work — a good target for any printed publication of your urban watercolors.",
        "quick_action": "Visit the Nakameguro shop, review what they currently stock, contact about consignment or publication pitch.",
        "submission_strategy": "publication_pitch",
        "submission_tone": "casual_introduction",
        "tags": ["nakameguro", "bookshop", "consignment", "art books", "Tier1"],
        "overall_score": 7.6,
        "differentiated_score": 7.6,
        "truth_aligned_score": 7.6,
        "painting_priority_score": 7.5,
        "source_purity_score": 8.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "MOUNT ZINE",
        "title": "MOUNT ZINE",
        "organization": "MOUNT ZINE",
        "category": "zine_shop_consignment",
        "category_label": "Zine Shop / Consignment",
        "city": "Tokyo",
        "country": "Japan",
        "official_website": "https://mountzine.com/",
        "source_url": "https://mountzine.com/",
        "one_sentence": "Tokyo's dedicated zine shop and small press hub — carries independent artist publications and serves as a year-round gateway to the Tokyo zine community.",
        "three_bullets": [
            "Zine-only focus means no competition from photography or fine art — watercolor zines are a natural fit",
            "Online store + physical presence = work reaches buyers beyond walk-in traffic",
            "Direct link to Tokyo Art Book Fair community and wider small press network"
        ],
        "why_this_fits_short": "If you make a watercolor zine, MOUNT ZINE is the obvious first place to stock it — the audience is exactly right and the barrier is low.",
        "quick_action": "Review their submission/consignment process on the website, prepare a PDF sample of a potential zine.",
        "submission_strategy": "publication_pitch",
        "submission_tone": "casual_introduction",
        "tags": ["tokyo", "zine", "small press", "consignment", "artist publication", "Tier1"],
        "overall_score": 8.0,
        "differentiated_score": 8.0,
        "truth_aligned_score": 8.0,
        "painting_priority_score": 8.0,
        "source_purity_score": 8.5,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
    {
        "name": "flotsam books",
        "title": "flotsam books",
        "organization": "flotsam books",
        "category": "bookstore_gallery",
        "category_label": "Bookshop / Art Books",
        "city": "Yoga, Tokyo",
        "country": "Japan",
        "official_website": "https://flotsambooks.com/",
        "source_url": "https://flotsambooks.com/",
        "one_sentence": "Tokyo's finest curated art and photography book shop — known for the quality of its selection and the cultural community it anchors, including a café and event program.",
        "three_bullets": [
            "Higher bar than MOUNT ZINE but correspondingly more prestigious — work stocked here has real curatorial weight",
            "Art book café format creates extended browsing time: viewers spend longer with books, more considered engagement",
            "Regular events create relationship-building opportunities with the photography and art book community"
        ],
        "why_this_fits_short": "The most credible Tokyo destination for art book consignment — more selective but worth pursuing as your printed work develops.",
        "quick_action": "Visit the shop, understand the curatorial sensibility, make contact when you have a polished publication to propose.",
        "submission_strategy": "publication_pitch",
        "submission_tone": "professional_introduction",
        "tags": ["tokyo", "art bookshop", "photobook", "consignment", "curator", "Tier1"],
        "overall_score": 7.8,
        "differentiated_score": 7.8,
        "truth_aligned_score": 7.8,
        "painting_priority_score": 7.5,
        "source_purity_score": 8.0,
        "career_tier": 1,
        "exclusive_primary_bucket": "immediate_best_moves",
        "primary_bucket": "immediate_best_moves",
        "difficulty": "low",
        "priority": "high",
        "recommendation_strength": "strong",
        "url_verification_status": "unverified",
        "verification_status": "unverified",
        "research_priority": "high",
        "manual_review_needed": True,
        "submission_process_known": False,
        "contact_verified": False,
        "fees": "none",
        "deadline": None,
        "predatory_risk": "none",
        "native_medium": True,
    },
]


def run():
    opps = json.loads(OPP_PATH.read_text(encoding="utf-8"))

    existing_names = {(o.get("name") or o.get("title") or "").strip().lower() for o in opps}

    added = 0
    for v in NEW_VENUES:
        key = (v.get("name") or "").strip().lower()
        if key in existing_names:
            print(f"  SKIP (already exists): {v['name']}")
            continue
        opps.append(v)
        existing_names.add(key)
        added += 1
        print(f"  ADDED: {v['name']}")

    OPP_PATH.write_text(json.dumps(opps, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nAdded {added} venues. Total opportunities: {len(opps)}")


if __name__ == "__main__":
    run()
