import sys, json
sys.stdout.reconfigure(encoding='utf-8')

path = 'deploy_data/compact_opportunities.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

existing_names = {(o.get('name') or o.get('title') or '').lower() for o in data}

new_entries = [
    {
        'name': 'BOOOOOOOM 2026 Art & Photo Book Award',
        'title': 'BOOOOOOOM 2026 Art & Photo Book Award',
        'organization': 'Booooooom',
        'category': 'group_publication_open_call',
        'category_label': 'Group Publication / Art Book',
        'city': 'Vancouver (international)',
        'country': 'Canada',
        'overall_score': 9.2,
        'differentiated_score': 10.8,
        'visual_fit_score': 3.5,
        'source_url': 'https://www.booooooom.com/2026/03/26/call-to-submit-2026-booooooom-art-photo-book-award/',
        'submission_page': 'https://www.booooooom.com/2026/03/26/call-to-submit-2026-booooooom-art-photo-book-award/',
        'official_website': 'https://www.booooooom.com/',
        'deadline': 'June 5, 2026 — 11:59 PM PST (June 6 at 15:59 JST)',
        'fees': 'Free (one zine proposal) / $25 USD (book proposal)',
        'deadline_verified': True,
        'fees_verified': True,
        'international_eligible': True,
        'one_sentence': 'Booooooom selects 6 book + 2 zine projects for free production annually — international, painting/illustration accepted, cohesive body of work required.',
        'why_this_fits_short': 'URGENT: June 5 deadline. International, painting OK, free zine submission. 8 projects get 25-100 free printed copies with full artist ownership. Tokyo Still Life or Urban Atmosphere body ideal.',
        'quick_action': 'Submit 10 images from one cohesive body of work + proposal paragraph at booooooom.com by June 5 11:59 PM PST.',
        'opportunity_type': 'group_publication',
        'action_type': 'apply',
        'recommendation_visibility': 'show',
        'verification_bucket': None,
        'tags': ['international', 'publication', 'book', 'zine', 'painting_ok', 'urgent', 'free_option'],
        'added_at': '2026-06-01',
        'last_verified': '2026-06-01',
        'source_type': 'manual_research',
    },
    {
        'name': 'Women United ART MAGAZINE Issue XIV Summer 2026',
        'title': 'Women United ART MAGAZINE Issue XIV Summer 2026',
        'organization': 'Women United ART MOVEMENT',
        'category': 'group_publication_open_call',
        'category_label': 'Group Publication / Magazine',
        'city': 'International',
        'country': 'USA',
        'overall_score': 7.8,
        'differentiated_score': 8.6,
        'visual_fit_score': 2.0,
        'source_url': 'https://www.womenunitedartmovement.com/artmagazine',
        'submission_page': 'https://www.womenunitedartmovement.com/artmagazine',
        'official_website': 'https://www.womenunitedartmovement.com/',
        'deadline': 'June 10, 2026',
        'fees': '$25 USD',
        'deadline_verified': True,
        'fees_verified': True,
        'international_eligible': True,
        'eligibility_note': 'Women artists only',
        'one_sentence': 'International coffee-table print magazine for women artists — all mediums including watercolor, deadline June 10, $25 fee.',
        'why_this_fits_short': 'Women-only international publication, watercolor accepted, June 10 deadline. $25 for a print magazine credit. GEGYjiji qualifies.',
        'quick_action': 'Submit work images at womenunitedartmovement.com before June 10. $25 fee. Hardship waiver available.',
        'opportunity_type': 'group_publication',
        'action_type': 'apply',
        'recommendation_visibility': 'show',
        'verification_bucket': None,
        'tags': ['international', 'publication', 'magazine', 'women_only', 'watercolor_ok', 'near_deadline'],
        'added_at': '2026-06-01',
        'last_verified': '2026-06-01',
        'source_type': 'manual_research',
    },
    {
        'name': "BALLOND'ESSAI Shimokitazawa",
        'title': "BALLOND'ESSAI Shimokitazawa",
        'organization': "BALLOND'ESSAI",
        'category': 'cafe_gallery',
        'category_label': 'Cafe Gallery / Wall Space',
        'city': 'Tokyo — Shimokitazawa',
        'country': 'Japan',
        'overall_score': 8.4,
        'differentiated_score': 9.5,
        'visual_fit_score': 3.0,
        'source_url': 'http://ballondessai.com/gallery/',
        'submission_page': 'http://ballondessai.com/',
        'official_website': 'http://ballondessai.com/',
        'deadline': 'No fixed deadline — ongoing, proposal-based',
        'fees': 'Unknown — confirm on contact',
        'contact_phone': '03-6804-7651',
        'contact_method': 'Website inquiry form at ballondessai.com',
        'address': '東京都世田谷区北沢2-30-11 1F',
        'hours': 'Weekday 11:30-21:00 / Weekend 10:30-21:00 / Closed Monday',
        'instagram': '@ballondessai.latte_art',
        'one_sentence': 'Shimokitazawa gallery-attached coffee stand with confirmed exhibition program — proposal via website form, back gallery space for rotating shows.',
        'why_this_fits_short': 'Gallery-first cafe in Shimokitazawa, confirmed accepts proposals via website, design-conscious audience, intimate scale. Direct contact path confirmed.',
        'quick_action': 'Submit exhibition inquiry via website form at ballondessai.com with portfolio link and proposed period.',
        'opportunity_type': 'relationship_target',
        'action_type': 'contact_and_propose',
        'recommendation_visibility': 'show',
        'verification_bucket': None,
        'tags': ['tokyo', 'shimokitazawa', 'cafe_gallery', 'exhibition', 'tier_1', 'proposal_based'],
        'added_at': '2026-06-01',
        'last_verified': '2026-06-01',
        'source_type': 'manual_research',
    },
    {
        'name': 'CLOUDS Gallery+Coffee Koenji',
        'title': 'CLOUDS Gallery+Coffee Koenji',
        'organization': 'CLOUDS Gallery+Coffee',
        'category': 'cafe_gallery',
        'category_label': 'Cafe Gallery / Wall Space',
        'city': 'Tokyo — Koenji',
        'country': 'Japan',
        'overall_score': 8.6,
        'differentiated_score': 9.8,
        'visual_fit_score': 3.5,
        'source_url': 'https://www.cloudsgallerypluscoffee.com/',
        'submission_page': 'https://www.cloudsgallerypluscoffee.com/',
        'official_website': 'https://www.cloudsgallerypluscoffee.com/',
        'deadline': 'No fixed deadline — rotating exhibitions ongoing',
        'fees': 'Unknown — confirm on contact',
        'contact_phone': '03-5356-9358',
        'contact_method': 'Phone or website — visit in person first recommended',
        'address': '東京都杉並区高円寺南4-42-4 コモンビル1F',
        'hours': '13:00-19:00 (final day 17:00) / Closed Monday',
        'instagram': '@clouds_koenji',
        'access': '2 min from JR Koenji Station South Exit',
        'one_sentence': 'Dedicated gallery + coffee in Koenji showing local and international artists in free-admission rotating exhibitions — confirmed international program.',
        'why_this_fits_short': 'Gallery-primary space with international artist program. Explicitly shows emerging and established artists from Japan and abroad. Best gallery-cafe match in Koenji.',
        'quick_action': 'Visit 13:00-19:00 any day except Monday to see current show. Then phone 03-5356-9358 or use website to propose exhibition.',
        'opportunity_type': 'relationship_target',
        'action_type': 'contact_and_propose',
        'recommendation_visibility': 'show',
        'verification_bucket': None,
        'tags': ['tokyo', 'koenji', 'cafe_gallery', 'exhibition', 'tier_1', 'international_program'],
        'added_at': '2026-06-01',
        'last_verified': '2026-06-01',
        'source_type': 'manual_research',
    },
    {
        'name': 'HATTIFNATT Koenji Cafe Gallery',
        'title': 'HATTIFNATT Koenji Cafe Gallery',
        'organization': 'HATTIFNATT',
        'category': 'cafe_gallery',
        'category_label': 'Cafe Gallery / Wall Space',
        'city': 'Tokyo — Koenji',
        'country': 'Japan',
        'overall_score': 8.2,
        'differentiated_score': 9.4,
        'visual_fit_score': 4.5,
        'source_url': 'https://www.hattifnatt.jp/',
        'submission_page': 'https://www.hattifnatt.jp/',
        'official_website': 'https://www.hattifnatt.jp/',
        'deadline': 'No fixed deadline — proposal-based',
        'fees': 'Unknown — confirm on contact',
        'contact_phone': '03-6762-8122',
        'contact_method': 'Phone inquiry, then in-person visit',
        'address': '東京都杉並区高円寺北2-18-10',
        'hours': '12:00-21:00 (L.O. 20:00) / Closed Monday and 3rd Tuesday',
        'instagram': '@hattifnatt__koenji',
        'access': '4 min from JR Koenji Station North Exit',
        'one_sentence': 'Koenji storybook-aesthetic cafe known for illustrators and warm interiors — highest aesthetic alignment with GEGYjiji of any cafe in the dataset.',
        'why_this_fits_short': 'The warmth, intimacy, cats, and interior light of GEGYjiji\'s work maps directly onto HATTIFNATT\'s storybook sensibility. Highest visual fit score in cafe category.',
        'quick_action': 'Phone 03-6762-8122 to ask about exhibition or wall display at the Koenji location. Visit first if possible.',
        'opportunity_type': 'relationship_target',
        'action_type': 'contact_and_propose',
        'recommendation_visibility': 'show',
        'verification_bucket': None,
        'tags': ['tokyo', 'koenji', 'cafe_gallery', 'illustration_friendly', 'aesthetic_match', 'tier_1'],
        'added_at': '2026-06-01',
        'last_verified': '2026-06-01',
        'source_type': 'manual_research',
        'research_note': 'Donguri Gallery is at Kichijoji location; Koenji display policy needs direct confirmation. Visual fit score reflects aesthetic alignment, not confirmed program.',
    },
]

added = []
for entry in new_entries:
    key = (entry.get('name') or '').lower()
    if key not in existing_names:
        data.append(entry)
        existing_names.add(key)
        added.append(entry['name'])
    else:
        print(f'Already exists: {entry["name"]}')

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'Added {len(added)} entries:')
for n in added:
    print(f'  + {n}')
print(f'Total: {len(data)} opportunities')
