"""Editorial decisions only. Does not change application source or data."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
EDITS = {}
def e(file, line, new, reason, kind='Rewrite', match=None):
    EDITS[(file, line, match)] = (new, reason, kind)

F = 'engines/futures_engine.py'
B = 'engines/book_economics_engine.py'
R = 'engines/recurring_calendar_engine.py'
O = 'engines/outreach_kit_engine.py'

# All complete Chinese prose units in Futures were read; neutral labels and
# numeric cells have explicit retained/review-required dispositions at render.
e(F,220,'你从 2020 年开始持续画水彩日记，也已经有了出版物、个展和自己的店铺。这些积累，可以继续用于出版、画廊合作和图像授权。\n\n下面整理了几种合作方式的收入来源、准备工作与实际入口，方便你比较：哪一种能用上现有作品，又符合接下来的创作安排。','Recognize concrete work; remove awkward business metaphor, false either/or route choice, and the requirement that every creative choice monetize.')
e(F,237,'印刷品与原作之间，可以尝试什么价位','Turn a supposed deficiency into a research question.')
e(F,239,'目前记录中的明信片、zine 和印刷品标价为 1,100–2,200 日元，原作从 31,900 日元起。中间价位可以作为一个产品试验方向，例如尺寸更大的艺术微喷或装裱印刷品。是否值得做，还需要比较样品质量、制作成本和实际订单。','Listed prices do not prove both ends sell. A price gap does not establish demand; multiple-item orders are also possible.')
e(F,253,'三种可比较的产品方案','Avoid commissioning three products as an implied instruction.')
e(F,254,'每件预计结余','You take home is not net profit; define included deductions next to table.',match='你拿到')
e(F,254,'结余占售价比例','Only use once numerator and denominator reconcile; see pricing blocker in brief.',kind='Hold for model correction',match='毛利率')
e(F,264,'按需印刷通常在收到订单后生产，可以减少预先备货。这里可以先比较一种产品的样品、色彩还原、费用和配送方式，再决定是否上架。前期仍可能有打样费，也需要准备图像和商品说明。','POD reduces inventory but is not zero effort or zero risk; remove claim that the factory absorbs all risk.')
e(F,274,'如果某种明信片已经有稳定订单，批量印刷可能更划算。比较时需要使用相同纸张、尺寸、印量和交付条件。新产品可以先小范围试卖，有了订单记录，再判断是否增加印量。','Avoid claiming knowledge of her sales or incomparable costs. Hold the 170/1,835 comparison pending like-for-like specifications.')
e(F,289,'销量还取决于哪些条件','Natural heading without pretending to isolate a causal driver.')
e(F,290,'已有案例可以帮助比较定价和产品形式，但不能直接推算你的销量。即使关注数量接近，读者所在地、购买习惯、书的规格和销售方式也可能不同。\n\n对印刷品来说，值得一起核算的是到手价格：售价、包装、运费及平台手续费。书的尺寸和厚度会影响可用的配送服务，因此最好在打样前一并比较。','Remove unmatched follower comparison, causal claims from tiny observational sample, and shipping quotes with different service conditions. Keep sourced cases in evidence detail, dated and named.')
e(F,310,'做成一本书，需要先确定哪些事','Replace vague other-level decision.')
e(F,311,'这份方案比较的是 128 页精装书的印制成本。印量、售价和销售渠道会共同影响需要预付的金额，以及收回这笔支出所需的销量。具体数字应在确认规格、运费和各项销售费用后计算。','Current 109-copy cash-recovery number double-counts production cost; do not polish it into a stronger claim.',kind='Hold for model correction')
e(F,324,'每本印制成本','Define unit cost.',match='每本')
e(F,324,'整批预付金额／印量','The cells include both cash outlay and quantity.',match='先要付')
e(F,325,'收回预付支出所需销量','Distinguish cash recovery from accounting margin.',kind='Hold for model correction',match='回本所需册数')
e(F,327,'B5 zine 方案，24 页','Do not call a model specification her current product unless verified.',match='现在的 B5 zine，24 页')
e(F,328,'{cash_recovery_copies}','Replace the hand-written 34 with a shared calculation. Pure prepaid printing divided by price, excluding all selling costs, gives ceil(49800/1980)=26; that diagnostic is not the final sales target.',kind='Hold for model correction',match='34')
e(F,330,'{cash_recovery_copies}','Replace the hand-written 173 with a shared calculation. The same simplified diagnostic gives ceil(482700/4400)=110, before all selling costs.',kind='Hold for model correction',match='173')
e(F,332,'{cash_recovery_copies}','Replace the hand-written 212 with a shared calculation. The same simplified diagnostic gives ceil(653000/4400)=149, before all selling costs.',kind='Hold for model correction',match='212')
e(F,338,'{cash_recovery_copies}','Use the corrected shared cash model, with explicit included costs and upward whole-copy rounding. Introduce the named field in the producing engine; do not paste this placeholder literally.',kind='Hold for model correction')
e(F,341,'用于销售的版本，需要比较印制成本、质量、运输和库存。用于提案的版本，可以先做少量样书，帮助出版社或画廊了解内容和编排。这两种用途适合分别询价。','Remove categorical cheapest conclusion and arbitrary three-copy command. Blurb quote belongs in dated specifications.')
e(F,356,'印制方案与收支测算','Current title mistakes run size for profit assurance.')
e(F,361,'pixivFACTORY／BOOTH：查看海报、画布和装裱印刷品的制作选项','Keep destination clear; avoid unsupported beginner/low-risk framing.')
e(F,364,'SUZURI：查看可制作的产品与费用','Do not imply every paper format is supported or costless.')
e(F,372,'INPRNT：查看艺术微喷的申请方式、分成和配送范围','Three-image/48-hour details need current platform verification before remaining in actionable copy.')
e(F,380,'比较画廊的投入与合作方式','Representation is not a promise that the gallery bears every risk.')
e(F,382,'你已有三场个展记录。接下来比较画廊时，可以进一步看它能提供哪些支持：展览空间、现场人员、作品介绍、销售，以及与藏家的联系。不同合作方式的费用和责任，可以放在一起比较。','Specific recognition without patronizing you already know how or prescribing a single next step.')
e(F,394,'艺术家承担的场地费','Zero venue fee is not zero total cost.',match='你付')
e(F,394,'销售佣金','Neutral professional label.',match='他们抽')
e(F,395,'覆盖场地费所需销量','Do not label this total break-even; packing, transport, labor and production are excluded.',match='打平前要卖掉')
e(F,401,'删除按原作标价折算销量的数值；费用比较保留日元金额。','Asking-price ranges do not establish net cash retained from her actual sales. This deletion is an implementation direction, not replacement UI text.',kind='Delete')
e(F,409,'删除按原作标价折算销量的数值；费用比较保留日元金额。','Do not convert public gallery terms into an implied personal break-even in paintings. This deletion is an implementation direction, not replacement UI text.',kind='Delete')
e(F,431,'Galerie LE MONDE 个展，可以怎样用于下一次介绍','Name the achievement and utility instead of vague what it left you.')
e(F,433,'你最近在原宿 Galerie LE MONDE 举办了个展。这段经历可以放进最新的作品资料：展览介绍、现场照片，以及同一组作品的链接，让下一位读者看到作品在空间中的呈现。','Keep appreciation grounded. Put verified gallery/agency context in separate sourced detail without implying representation or inherited client relationships. Remove mind-reading, urgency tied to diminishing freshness, and an unprompted caveat that diminishes the achievement. Historical fees are not her personal invoice.')
e(F,456,'可以进一步了解的相关机构','Same-building detail must be verified; utility is the service, not a pretext to revisit.')
e(F,458,'Studio LE MONDE：孔版印刷工作室。可查看制作项目、预约方式和当前营业时间。','Exact schedule and contact should come from maintained official link, not long-lived prose.')
e(F,461,'Agence LE MONDE：可查看其代理插画师及合作案例。是否接受申请，以当前官方说明为准。','Do not imply exhibition guarantees consideration or quietly inherit another artist’s client list.')
e(F,466,'按“场地费 374,000 日元＋销售佣金 30%”与“无场地费＋销售佣金 50%”这两种假设比较，在其他条件相同的情况下，销售总额约 187 万日元时，两者的场地费和佣金合计相同。\n\n实际选择还需要看画廊提供的服务、合作范围和买家来源。这里比较的是费用结构，不是对某次展览价值的评价。','Make comparison explicitly hypothetical and like-for-like; do not infer how her buyers found her.')
e(F,478,'联系前可以准备的资料','An available starting point rather than an order.')
e(F,479,'一组方向一致的作品链接，加上近期个展的介绍和现场照片，可以作为联系材料。是否先到访、提交 PDF 或填写表单，按每家画廊公开的要求准备。','Respect actual submission routes rather than universal visit-then-email etiquette.')
e(F,498,'FACE 2027：本轮报名截至 2026 年 10 月 8 日','Explicit year; status must expire automatically.')
e(F,500,'FACE 2027 的报名期为 2026 年 9 月 7 日至 10 月 8 日，报名费 7,000 日元，接受水彩等平面作品。作品须在出品前一年内完成，且未曾在公开征集中入选；每人限投一件。\n\n申请前需要核对尺寸、厚度、重量及送件要求，并另计包装和运输费用。U30 Frontier 奖面向 1997 年 4 月 1 日及以后出生的参赛者。','Official SOMPO page verified 2026-09-10. Missing work-age and prior-selection restrictions matter; after -> inclusive date. Link detailed handling schedule instead of claiming delivery is the only hurdle.',kind='Rewrite with verified source')
e(F,524,'三家可进一步了解的东京空间','Existence and thematic resemblance do not prove acceptance of her work.')
e(F,526,'HAGI ART 的公开介绍涉及展览、艺术书和建筑与日常生活等主题，可作为核对展览提案要求的对象。\n\nGallery KAZE 与 Moon Gallery 可用于比较租赁展览的费用和服务。费用表应注明查询日期、展期、销售佣金、值守安排及额外收费；某一时点的空档不代表仍可预约。','Move volatile prices/availability into dated facts; do not imply all are equally suitable, or that her Moon terms equal public rates.')
e(F,548,'HAGI ART：查看展览提案要求与官方联系渠道','Retain exact materials/address only after current route check.')
e(F,551,'Gallery KAZE：查看场地、收费和设备说明','Replace unqualified rate promise with maintained source.')
e(F,556,'可留意下一轮的公开征集','Do not promise annual recurrence from a short history.')
e(F,559,'biscuit gallery 的 grid next 可作为下一轮关注项目。申请资格、作品发表限制和收费情况，需要按当届要项核对。下一轮尚未公布时，仅显示往届报名时间作为参考。','Remove fixed age, fee and opening claims unless current source supports each. Neither past dates nor recent annual pattern confirms next cycle.')
e(F,564,'更长期的画廊参照','Remove hierarchy of ceilings and unreachable upper market.')
e(F,566,'Tokyo Gallery + BTAP 可作为更长期的研究参照：看看它如何介绍纸上作品、安排展览和呈现艺术家的长期创作。媒介相近，只是进一步了解的起点；是否适合合作，还需要比较具体作品与画廊方向。','Avoid making nationality/medium a proxy for fit, or declaring a gallery impossible to approach.')
e(F,578,'也可以比较提供制作支持的展览项目','Third is universally cheaper is not established.')
e(F,580,'提供制作支持的公开征集，是另一种办展方式。例如 TOKAS-Emerging 的当届要项列有场地和制作支持。它需要经过评选，资助范围与艺术家承担的工作应分别列明。','Support is neither a sales opportunity nor complete risk transfer.')
e(F,597,'下面按合作方式整理了相关机构，便于比较它们的展览、出版或授权业务。','Replace universal ten-versus-hundred slogan. The finished records must actually supply the fit explanation and verified route; do not publish instructions to the system as product copy.')
e(F,606,'下面是一封写给 HAGI ART 的日语联系草稿。使用前需要补齐真实的到访经历或选展理由，并按对方当前要求调整材料。','Clarifies draft status; title alone does not make copy safe to send.')
e(F,633,'现有作品的授权用途','Plain, professional heading.')
e(F,634,'你已有的水彩作品，可以按书封、文具、日历等用途整理授权样例。能否授权，需要先确认作品权利和图像文件；费用则取决于具体用途、期限、地域与独家要求。','Do not infer thousands of licensable high-resolution images from years of practice. Remove reuse of commission grid as archive-license price list.')
e(F,645,'历史制作报价参考（2020 年）','JIA table is commissioned illustration, not current archive-license market rates; preferably relocate to commissions.',kind='Move / correct scope',match='公开费率')
e(F,647,'删除该行；5,000 日元仅对应特定规格的小幅插图，不能代表所有杂志内页图。','Delete overgeneralized amount, not replace with invented new rate.',kind='Delete',match='5,000 日元')
e(F,650,'A3 挂历插画，全套 12 幅','800,000 row is a 12-image commissioned set, not one licensed painting. Relocate with source/date.',kind='Move / correct scope',match='挂历')
e(F,653,'报价时可同时列出用途、地域、期限、是否独家，以及追加使用的处理方式。长期使用许可和著作权转让涉及不同范围的权利，应在条款中分别写清楚。','Do not equate perpetual license with ownership. JIA multiplier belongs to source detail, not a universal contract rule.')
e(F,664,'从现有作品中挑选书封样例','Avoid turning research on existing assets into a request for ten new paintings.')
e(F,665,'你的建筑、室内和光线题材，可以用来研究书封的呈现方式。先从现有作品中挑几张，试排书名、作者名和必要文字，看看裁切后能否保留画面的重点。需要新作品时，再按具体用途补充。','Keep practical art-direction value; remove promise of commercial fit and unnecessary production.')
e(F,686,'イラストレーションファイルWeb：查看插画师资料及申请收录方式','Avoid universal claim about all art directors.')
e(F,689,'amanaimages：查看书封图像的授权范围与报价示例','Buyer-facing price not artist payout.')
e(F,692,'Arcangel：查看书封图像征集及供稿合同','Net receipts definition and deduction basis must be documented.')
e(F,699,'Bridgeman Studio：查看插画申请材料与合同选项','Exclusivity claims should quote current contributor agreement, not imply unrestricted reuse.')
e(F,704,'可以先用现有作品了解需求，再根据实际询问决定是否补充新作。','Clear conditional sequence.')
e(F,713,'把已有作品整理成出版提案','More immediately useful than an unmade-book abstraction.')
e(F,715,'出版提案需要让编辑看清这本书的主题、读者和内容结构。你已有的作品可以作为样例；还没完成的部分，则在方案中说明。这样对方能评估选题，而你也不必先把整本书画完。','Remove unverifiable reader response and unidentified comparison book; preserve the valuable reduction in up-front work.')
e(F,733,'主题与书名暂案','More useful proposal field.')
e(F,735,'按阅读顺序编排的样页','Natural publishing Chinese.')
e(F,736,'能体现画面风格的完成作品','视觉语言 is acceptable but less direct here.')
e(F,739,'预计页数、开本与制作进度','Concrete scope.')
e(F,742,'六年的日常创作，为选题、样页和作品编排提供了现成素材。','Specific appreciation without grading her as especially solid.')
e(F,748,'版税、发行与前期投入','Name what is being compared.')
e(F,749,'出版社合作与自出版，需要分别比较每本收入、前期投入和发行支持。','Avoid assigning weak/strong universal properties.')
e(F,754,'售出 300 本的测算','Clarify assumption; do not imply forecast.',match='300 本')
e(F,754,'每本收入及扣费口径','Publisher royalty and self-publishing contribution are not apples-to-apples until cost basis aligned.',kind='Hold for model correction',match='每本你拿到')
e(F,769,'出版社可承担编辑、设计、印制、库存及发行中的一部分或全部工作，具体以合作方案为准。自出版则需要自行安排这些环节。两种方式可以用同一套口径比较：前期现金投入、每本结余、工作量和发行渠道。','No automatic nationwide stocking, ISBN uniqueness, or guaranteed permanent career benefit.')
e(F,788,'前期印制费用由谁承担','Do not repeat a provisional model number as a firm invoice.')
e(F,790,'三家出版社，各自的联系方式','MdN has an inquiry route, not an open proposal call.')
e(F,798,'マール社：可查看公开的出版提案要求、费用承担方式和回复说明。','Submission response not promised by us; retain sourced detail in dated evidence.')
e(F,801,'青幻舎：可通过出版提案专用表单查看材料要求与附件限制。','Do not assume current 10 MB limit without check.')
e(F,804,'MdN：出版过《東京店構え》等相关题材书籍。目前未确认有公开提案入口，可先查看官方咨询方式。','Proper book title; inquiry is a question, not invitation to send unsolicited large files.')
e(F,809,'可以先整理一份通用的选题说明和样页，再按各出版社的书目与材料要求分别调整。','Do not pretend all three accept same submission.')
e(F,819,'把创作工作与使用范围写清楚','Distinguish quote components without universal mandatory separate invoices.')
e(F,821,'商业委托可以按创作工作、使用范围和交付条件来比较。历史报价表能提供参考，但需要注明年份、作品规格与适用范围。','No official national minimum; historical evidence not binding floor.')
e(F,831,'历史制作报价参考（2020 年）','Current rates cannot be inferred from old table.',match='公开费率')
e(F,836,'删除此行，或另列具名调查的年份、样本和统计口径。','71,327 has false precision and no visible population; not same kind of evidence as commission guideline.',kind='Hold for source',match='经手工作的平均值')
e(F,839,'书籍封面是可以进一步研究的用途。报价时，需要把原稿制作与追加使用分别说明；公开参考表中的金额和比例，也应连同年份、作品规格及适用条件一起展示。','Do not turn a workload rank into a prestige rank or universal formula; cite JIA once in evidence appendix.')
e(F,859,'可以复用的报价说明','Avoid assumption nobody has approached her.')
e(F,861,'一份清楚的报价说明，可以包含以下四部分：','Available structure, not dictate to every deal.')
e(F,868,'创作内容、交付文件、修改次数与交付时间。','Specific scope she can reuse.')
e(F,870,'使用媒介、用途、地域、期限及是否独家。','Include exclusivity; clear standard terminology.')
e(F,873,'增加媒介、延长使用时间或扩大范围时，如何另行约定费用。','Avoid implying every different use automatically has same fee rule.')
e(F,876,'如需转让著作权，单独列明权利范围和对价，并确认作品展示及后续使用安排。','Ownership and indefinite license must not be conflated; final terms need case review.')
e(F,884,'有了这份说明，收到询问时就可以按项目调整，不必每次从头写。','Concrete time saved.')
e(F,890,'两项可查看当届规则的作品征集','Not always currently open.')
e(F,896,'ザ・チョイス：查看当期评审、报名费用、付款与寄件截止时间。','Time-sensitive quantities belong to dated factual fields.')
e(F,899,'HB FILE：查看当届作品集要求、费用、展示方式和奖项。已有作品是否可用，以该届规定为准。','Do not promise complete portfolio from all past work, or stale edition number.')
e(F,904,'这两项征集可以帮助作品接触编辑与设计从业者。是否值得参加，需要结合当届评审、费用和准备量判断。','¥7,000 not objectively cheap; competition does not guarantee commission.')
e(F,914,'可以从哪一步开始','Plain next-action heading.')
e(F,923,'下面按准备工作的先后整理。可以先选一个方向；有截止日期的项目另列出来，方便安排。','Current body has six rows but says five experiments; no need to do every route.')
e(F,928,'有明确截止日期','Date supplied by data, not static heading.')
e(F,929,'FACE 2027：先核对作品是否符合当届要求，再决定是否报名。报名截止、费用和送件安排见项目详情。','A calendar exception, not automatic first recommendation.')
e(F,932,'先比较一种印刷品的打样费用与预期售价，再决定是否制作样品。','One product; no unsupported afternoon estimate.')
e(F,935,'整理近期个展的介绍、现场照片和一组作品链接，供下一次联系使用。','Useful existing-materials step; visit not magically one afternoon.')
e(F,938,'从现有作品中挑选几张，试做书封或文具的排版样例。','Replace “头五张” and obligation to make new work.')
e(F,941,'选一组已有作品，写出一页选题说明，并配上几页样页。','Concrete deliverable.')
e(F,944,'准备一份可以复用的报价说明，列明创作内容、使用范围和修改安排。','Do not infer no inquiries yet.')
e(F,947,'先完成与你当前方向最相关的一项，再根据实际反馈决定下一步。','Remove belittling 凭空挑选 and five simultaneous experiments.')
e(F,979,'合作方式','Remove verbose formula repeated five times.')
e(F,980,'可以带来什么','Remove unjustified exclusivity.')
e(F,981,'需要投入什么','Less burdensome without concealing real tradeoffs.')
e(F,1001,'通过自己的店铺销售，可以自行安排产品、定价和上架节奏。明信片、zine、印刷品与原作的销售，可以沿用已有渠道。','No elementary lecture about money arriving one item at a time.')
e(F,1017,'已有店铺和关注者，让你可以用现有渠道介绍新产品。定价与上架安排也由你掌握。收入需要扣除制作、平台、包装、配送等实际费用，订单多少则需要通过销售记录来判断。','Remove “only this route,” next-Friday earnings, assumed reach and take-home/profit conflation.')
e(F,1034,'上架、拍照、客户沟通和履约仍需要时间。批量印刷通常要先付款并安排库存；按需印刷则需要比较较高的单件费用和供应商的交付质量。','No claim all sales come from followers or all channels decline together.')
e(F,1045,'不同画廊提供的支持有所不同，可能包括策展、作品介绍、销售与藏家联络。合作时需要明确场地费、销售佣金和双方责任。','No inevitable price rise or all collectors repeat.')
e(F,1054,'合适的画廊合作，可以增加作品被认真介绍和接触新买家的机会。展览资料也可以用于之后的出版或委托介绍，具体价值取决于展览内容与合作方式。','Specific possible benefit, no universal prestige transfer.')
e(F,1067,'需要比较销售佣金、费用承担、展期安排及合作范围。建立长期关系可能需要多次交流，时间和结果都因画廊而异。','Remove fatalistic shared quiet year and fixed months-long script.')
e(F,1077,'图像授权让合作方在约定范围内使用作品，并负责相应产品的制作或发行。报价与条款需要写明用途、期限、地域和独家要求；原作所有权也应单独确认。','“安静的钱” sells passive income; use precise mechanism.')
e(F,1086,'现有作品有机会用于不同产品；能否重复授权，取决于已有合同和每次约定的范围。整理作品、沟通用途和审核合同仍需要时间。跨地区合作还需确认适用的合同、税务与当地规定。','Remove false exclusivity, no-publicity promise, and unsafe visa-minimal blanket claim. No inference about her immigration status.')
e(F,1100,'收入可能来自一次性授权费，也可能按销售结算。不同艺术家的收入构成差别很大，个案只能作为参考。长期或独家条款会影响后续使用，因此需要明确权利范围、期限与终止条件。','One artist’s 3% is not market rate; perpetual transfer and exclusivity not identical.')
e(F,1114,'与出版社合作时，可以由双方约定选题、编辑、制作和发行分工。需要先确认是由出版社承担成本的出版合作，还是包含作者出资的其他模式。','Distinguish supported publishing from author-funded arrangements without assuming contract.')
e(F,1122,'出版社可能提供编辑制作、书店发行和库存管理等支持，让作品接触店铺之外的读者。一本内容清楚、编排完整的书，也能作为介绍创作的材料。具体渠道与投入，以对方的合作方案为准。','No guaranteed national distribution or claim self-publishing readers never see posts.')
e(F,1139,'需要投入提案与样页准备，并等待编辑评估。后续还要确认制作周期、修改安排、版税结算和权利范围。自出版则需要自行安排制作与销售，同样有时间和现金投入。','Acceptance is not only uncertainty; self-publishing not instantaneous.')
e(F,1151,'商业委托通常围绕具体项目展开。费用可综合创作难度、修改量、交付时间和使用范围商议，付款节点也需要事先约定。','Hours and scope both matter; no guaranteed payment sequence.')
e(F,1158,'确认委托后，可以按约定的项目和付款节点安排工作。持续合作的客户有助于提高可预期性，但每月收入仍取决于订单与结算。','Remove guaranteed monthly income, universal prepayment and dismissive “最不浪漫”.')
e(F,1170,'需要留出沟通、修改和交付的时间，并确认作品能否继续展示或使用。与原作销售比较时，应同时考虑实际结余、投入时间和保留的权利。','Original list price and commission net return not comparable; no shaming portfolio slogan.')
e(F,1199,'沿用自己的店铺，安排产品和定价。','No implied net-profit guarantee.')
e(F,1206,'比较展览支持、销售服务与合作费用。','Tell her what useful research is inside.')
e(F,1213,'看看现有作品还可以用于哪些产品。','Preview usefulness.')
e(F,1220,'把作品整理成选题，了解出版社如何接案。','No cost-bearing promise before contract.')
e(F,1227,'整理作品资料与报价，准备回应项目询问。','No elementary definition; useful content preview.')
e(F,1268,'你已有自己的店铺，也在多个平台积累了关注。这里比较印刷品的制作成本、定价和销售方式。','Remove sum of follows = people watching, and deficiency framing.')
e(F,1279,'已有 {solos} 场个展和 {groups} 场已确认联展，最近一场是 {latest_exhibition}。','Introduce latest_exhibition from the current verified record; omit that clause when unavailable. Counts must not silently become zero. This is a template proposal, not a drop-in source patch.')
e(F,1287,'建筑、室内与光线题材，可以用于研究书封、文具和空间装饰类的合作。','No claim character artists cannot enter huge overlapping categories.')
e(F,1291,'已有 {zines} 本 zine 和 {pubs} 本出版物，也有六年的水彩日记可供整理。','Counts are source-driven; remove automatic “enough for a book” judgment.')
e(F,1295,'持续的水彩创作，已经积累出可供编辑了解的作品。这里整理介绍材料与报价方式。','Daily self-directed practice is not client deadline performance.')

# Print-model prose. Numeric outcomes are withheld until arithmetic/specs fixed.
e(B,76,'按当前估算包含运抵东京的费用；最终以同一规格的书面报价为准。','Chinese language does not guarantee a lower price; landed terms require confirmation.')
e(B,83,'这项方案按供应商的尺寸、页数与交期范围估算，最终规格和交付时间需另行确认。','B5/96-page route is not equivalent to 128-page hardcover; show spec in comparison.')
e(B,90,'日本 A4 胶印方案；需核对纸张、页数、装订和交付费用。','Remove assumptions about what most people believe.')
e(B,200,'提高定价会改变收回预付支出所需的销量，也可能影响需求。可以把不同售价作为测算情景，比较各自的条件。','Hardcoded 41 differs from computed value and faulty model; no guaranteed rescue by pricing.',kind='Hold for model correction')
e(B,211,'印制成本可以先询价，销量和销售速度则需要通过实际订单了解。这里把预付支出、销售费用和不同销量下的结果放在一起，帮助比较自出版与出版社合作。','Not precise to yen before quote; not all uncertainty unknowable.')
e(B,226,'达到测算中的销量后，销售回款可覆盖模型列出的预付支出。之后的每笔订单仍可能产生平台、包装和配送费用；最终收益也取决于实际售出数量。','Remove assured recovery, “only slow,” and remaining stock = pure profit.',kind='Hold for model correction')
e(B,237,'前期费用由谁承担','Avoid promoting provisional number.')
e(B,240,'预付支出','Natural cash-flow term.')
e(B,241,'收回预付支出所需销量','Define metric consistently.')
e(B,242,'每本收入与扣费口径','Avoid gross/net mismatch.')
e(B,243,'发行渠道','Precise heading.')
e(B,244,'库存与履约','Professional rather than books in bedroom.')
e(B,245,'仍需确认的条件','More than one unknown.')
e(B,252,'按所选规格、印量和交付条件计算的预付费用。','Real amount must regenerate from corrected model.',kind='Hold for model correction')
e(B,254,'按实际单笔回款计算，显示收回整批预付支出所需的销量。','Remove remaining copies pure profit.',kind='Hold for model correction')
e(B,256,'按直售价格扣除模型列明的销售费用后计算。','Define costs once; do not subtract prepaid production cost twice.',kind='Hold for model correction')
e(B,258,'自己的店铺，以及已确认接受寄售或参展的渠道。','No assumed consignment acceptance.')
e(B,260,'需要安排库存空间、包装和发货，也可询问仓储或代发服务。','Avoid dramatized books piled in room.')
e(B,262,'实际订单量与销售周期。','Unknown timing without faulty threshold.')
e(B,268,'出版社承担制作与发行的合作','Distinguish contract models.')
e(B,270,'是否需要作者出资，以合作方案为准。','No universal zero-cost guarantee.')
e(B,271,'如无作者预付制作费用，则无需回收这笔制作支出。','Still time/opportunity cost; specify cash item.')
e(B,272,'版税收入需按合同中的计价基数、比例和结算方式计算。这里的示例只是测算情景，尚无出版社向你提出具体条件。','Do not treat 8–10% as universal Japanese rate or compare gross royalty to inconsistent margin.')
e(B,278,'合同中约定的书店及线上发行渠道。','Nationwide book distribution not guaranteed placement.')
e(B,279,'库存由谁保管、退货如何处理，以合同约定为准。','Publisher warehouse not universal.')
e(B,280,'选题是否采用，以及制作、权利和结算条款。','Acceptance not sole unknown.')
e(B,284,'Mateusz Urbanowicz 与 MdN 的合作，可以作为城市水彩出版的案例。值得研究的是选题、样页和发行方式；个案销量不能直接推算你的销量。','Remove false claim self-publishing has no path to 100k; publication example not sales forecast.')
e(B,296,'销售速度：目前能参考什么','Distinguish known case from forecast.')
e(B,298,'已有参展者案例可用于了解书展销售，但样本中的销量不能代表整个市场。比较时需注明书展、展期、产品价格、样本数量和统计方式。','Mixed self-selected sample not national art-book-fair median.')
e(B,302,'参展费用需要单独计算：展位、交通、运输和值守等支出，再除以每本新增销售带来的净回款。这个数表示覆盖参展费用所需的销量，不能据此推算多久能卖完。','Delete first-hour prediction; distinguish incremental event cost from run cash recovery.',kind='Hold for model correction')
e(B,306,'寄售分成会影响每本回款。可以在相同售价和成本条件下，分别测算直售与寄售，再决定印量和渠道。','Fixed ¥1,500 universal threshold does not follow from supplied numbers.',kind='Hold for model correction')
e(B,329,'计算条件与明细','“算法” is internal implementation vocabulary.')
e(B,330,'每项测算都列明规格、费用来源、查询日期和未计入的支出。','Replace false unique knowable-price assertion.')
e(B,333,'这些数字用于比较方案。供应商报价、实际订单及未计入的费用变化后，结果也需要更新。','No “every figure sourced” blanket; disclose limitations at point of use.')

# Only rule[4] from outreach is mounted in current Saffron, plus Japanese letter.
e(O,75,'暂时没有回复，原因可能很多。是否再次联系，可以结合对方公开的联系说明，以及你是否有新的展览或作品消息来决定。','Silence is not evidence an email was unseen. Never manufacture a second visit or scheduled repeated outreach.')

# Every recurring entry, including other months, read from source.
e(R,59,'TOKAS-Emerging','Do not misname Tokyo Arts and Space as Museum of Contemporary Art Tokyo.')
e(R,62,'2027 年度要项提供免费场地、15 万日元制作支持，以及部分布展、运输和宣传支持。申请者须在日本居住，并于 1991 年 4 月 1 日及以后出生；该轮已截止。下一轮条件以新要项为准。','Official page verified: birth cutoff is 1991, not 1990; support is partial, not all tasks done.',kind='Rewrite with verified source')
e(R,73,'按当届要求准备展览方案与作品集，说明作品如何在空间中呈现。','Do not invent ten-image universal requirement.')
e(R,87,'下一轮开放情况需以 TOKAS 官方公告为准。','Source archive lists OPEN SITE 11 in February 2026; verify claimed suspension against precise cycle before retaining.',kind='Hold for source')
e(R,91,'制作支持金额、展览形式和申请资格，按当届要项列明。','Separate historical allowance from future promise.',kind='Hold for source')
e(R,95,'一组相关作品，以及空间使用和展示方式的说明。','Natural preparation language.')
e(R,107,'TOKAS 驻留项目（国内／交流）','驻留 is standard; different programs must be separate entries.')
e(R,111,'国内驻留与海外交流的地点、时长、经费和资格不同，需分别查看当届要项。','Do not merge several programs into one universally eligible offer.',kind='Hold for source')
e(R,115,'研究主题、选择该地点的原因，以及计划开展的交流或创作。','Concrete proposal elements; no rhetorical question.')
e(R,128,'评审制展示项目。报名费用、展位规格、奖项与资格，需按当届要项核对。','Current event fees and awards need maintained source.',kind='Hold for source')
e(R,132,'一组适合展位尺度的作品，以及展示布局和作品说明。','“一眼看住” is unnatural; do not prescribe spectacle to quiet painter.')
e(R,144,'可用于了解独立艺术家的展示与行业交流机会。参展费用、筛选方式和评审名单需按当届公告确认。','Remove unsupported recognized pipeline and static juror count.')
e(R,148,'一组方向连贯的作品，以及一段简短的创作介绍。','No prediction of what every gallery owner asks.')
e(R,164,'申请资格、入选名额与获奖后的展览安排，以当届要项为准。','Current sentence ambiguously awards solo shows to all ten; verify categories.',kind='Hold for source')
e(R,168,'按当届要求整理作品集，并说明作品的关联与应用方向。','Do not generalize jury roles or portfolio count.')
e(R,183,'可查看下一轮的申请资格、收费及入选后的展览安排。','Need latest conditions rather than permanent age/fee promise.')
e(R,187,'申请前核对作品的发表限制；如要求未发表，需确认社交平台展示是否包含在限制内。','New painting and Instagram embargo cannot be commanded from assumed rule.')
e(R,197,'可比较制作支持、空间使用和项目执行要求。金额与支持期限按当届要项列明。','Remove superlative across Japan and fixed unverified support.',kind='Hold for source')
e(R,201,'一份包含创作主题、实施计划、预算和成果呈现方式的项目提案。','Project grants not blanket ban on existing work.')
e(R,212,'Arts Council Tokyo「スタートアップ助成」','创业期扶持金 misleadingly sounds startup-business grant; retain official title.')
e(R,216,'这类资助支持在东京开展的艺术活动。申请资格、补助上限和可计入的费用，应按当轮指南分别确认。','Retain useful project-cost distinction without assuming eligibility or recurring rounds.')
e(R,220,'活动方案、实施时间、预算，以及已确认的场地或合作安排。','Avoid invented already-planned-project requirement.')
e(R,234,'需按具体资助类别核对活动地点、申请人资格、经费上限与可支持的项目。','Do not universalize no nationality/age/residence constraints across categories.',kind='Hold for source')
e(R,238,'按所申请类别准备项目方案；涉及跨地区合作时，说明双方分工与合作安排。','Two-location requirement not established for whole foundation.')
e(R,255,'ACC 的个人奖助支持符合条件的研究与文化交流。申请资格、目的地、时间和在读期间的安排，需按当届指南逐项确认。','Nationality alone does not settle eligibility; current official page does not substantiate blanket five-year rule.')
e(R,259,'如计划涉及休学或长期离境，需向学校和相关机构确认具体安排。','Do not infer her current visa; no categorical immigration ruling.')
e(R,263,'研究计划、拟联系的机构与推荐材料。准备时间取决于项目范围和材料要求。','No universal three-month preparation claim.')
e(R,270,'荷尔拜因（Holbein）奖学金','Correct established Chinese brand spelling; retain Japanese official name if region preference differs.')
e(R,273,'画材支持项目。支持品类、金额、申请资格和材料要求，需查看当届公告。','Do not make medium sufficient for eligibility.',kind='Hold for source')
e(R,277,'按当届要求整理作品、创作说明和所需画材。','Remove “almost no preparation” assumption.')
e(R,287,'美术馆驻留项目。需确认当届面向的申请地区、资格、驻留安排与成果要求。','Asian-targeted and unrestricted nationality/residence are not equivalent.',kind='Hold for source')
e(R,291,'说明研究或创作主题、与当地的关联，以及驻留期间的计划。','Do not assume her practice consists of moving between two cities.')
e(R,304,'艺术书、zine 与独立出版物的展示和销售场合。展位费用、展期和参展要求按当届公告列明。','Cheapest historical booth is not available to all applicants.')
e(R,308,'2027 年 1 月这一届的申请已截止。下一轮开放时间需等官方公布，往届月份仅供准备时参考。','Closed applications not proof fully booked; avoid invented next opportunity.')
e(R,312,'可展示和销售的出版物，以及定价、库存、配送和值守计划。','No fixed three-month or afternoon estimate.')
e(R,331,'面向具象艺术创作的资助。年龄、申请资格、支持金额与材料要求，需查看基金会当前说明。','Specific age boundary and unrestricted scope need source check.',kind='Hold for source')
e(R,335,'可先整理近期作品图片与创作说明，再按基金会当前申请清单补齐材料。','Rolling does not mean no detailed requirements.')

LADDER_EDITS = {}
def l(path,new,reason): LADDER_EDITS[path]=(new,reason)
l('STATES.g_publication.detail','《Colour Diary》由持续的水彩日记整理而来，已成为你的出版经历之一。','Avoid unverified translated title/date and awkward 出版的那一半成立.')
l('STATES.g_group.detail','已有 8 场已确认联展，展出地点包括上海、广州和东京。','Count should be derived; no faint praise about first outing.')
l('STATES.g_institutional.detail','曾在天津棉美术馆和台州横渡美术馆参加展览。这些经历可以连同项目介绍与现场资料一起收入作品集。','Institution != no commerce; do not demean commercial venues.')
l('STATES.g_solo.label','已举办个展','Remove 包括在东京 as dangling translation.')
l('STATES.g_solo.detail','已有三场个展记录，最近一场在原宿 Galerie LE MONDE，于 2026 年 9 月 6 日结束。可用展览介绍和现场照片呈现这一组作品。','Recognition plus usable evidence; preserve official title separately, no invented translation.')
l('STATES.g_international.label','在更多地区展出','Chinese artist in Japan already international; London is not start of all international work.')
l('STATES.g_international.detail','2025 年 12 月曾在伦敦展出，作品也由此接触到中日之外的展览环境。','Precise geographic claim.')
l('STATES.g_press.label','关于作品的采访与评论','Positive name; not downgrade existing press.')
l('STATES.g_press.detail','已有报道以作品介绍为主。未来如有围绕创作展开的采访或评论，可以与现有报道一起整理，帮助读者了解作品的背景。','No single mandatory next rung or unsupported curator requirement. Count mismatch 2 vs 3 must be reconciled.')
l('STATES.g_representation.label','持续的画廊合作','Representation is an option, not universal goal.')
l('STATES.g_representation.detail','可以比较画廊提供的展览、销售和藏家联络支持，再判断合作范围是否适合自己的创作安排。','Remove largest possible step and guaranteed price rise.')
l('STATES.g_fairs.label','进一步的展览与艺博会机会','更强 describes prestige as personal score.')
l('STATES.g_fairs.detail','不同艺博会和机构展览有各自的参与方式。有些通过画廊，有些接受独立申请，需要分别核对。','Not a fixed ladder dependency.')
l('STATES.a_cadence.label','持续的水彩日记','No obligation never to stop.')
l('STATES.a_cadence.detail','从 2020 年开始的水彩日记，已经积累成可用于展览、出版和作品介绍的素材。','Avoid unsupported most artists fail comparison.')
l('STATES.a_look.label','逐渐清晰的画面风格','Less mechanical thumbnail criterion.')
l('STATES.a_look.detail','城市建筑、室内光线和水彩的透明感，在你的作品中持续出现。这些关联可以帮助整理作品系列与对外介绍。','Specific appreciation; recognize not guaranteed audience response.')
l('STATES.a_found.label','多个平台上的关注者','No assumptions about acquisition.')
l('STATES.a_found.detail','你在 X、微博、小红书、Instagram 和 B 站都有关注者。各平台数量可分别展示，并注明记录日期；跨平台关注会重叠，不能直接当作独立人数或实际触达。','No claim none paid; followers not reach.')
l('STATES.a_series.label','已有名称的作品系列','Remove negation and belittling accumulation.')
l('STATES.a_series.detail','《一天和四季》《彩色日记翻翻乐》《365日永恒如新》已有名称与编号，可以继续用于整理视频、出版选题或系列介绍。','Concrete recognition without claiming proven retention.')
l('STATES.a_motion.label','已记录的作画过程','Grounded possession rather than audience mind reading.')
l('STATES.a_motion.detail','你已经拍摄并在 B 站发布作画过程。视频保留了成画之外的变化，例如水分、颜料和笔触如何逐步形成画面。','Do not infer every follower’s reason.')
l('STATES.a_motion.treatment.open','这些视频还可以怎样使用','Remove levels.')
l('STATES.a_motion.treatment.blocks.0.label','视频能补充什么','Useful heading.')
l('STATES.a_motion.treatment.blocks.0.text','过程视频可以呈现水彩在纸面上的变化，也让读者看到作品如何完成。它与成画可以互相补充。','Remove no competition, impossible screenshot, only uniquely hers claims.')
l('STATES.a_motion.treatment.blocks.1.label','已有素材，可以少做哪些准备','Recognize existing labor.')
l('STATES.a_motion.treatment.blocks.1.text','已有录像可以减少重新拍摄的工作。整理时仍需确认文件、画幅、声音和字幕，再决定哪些适合直接使用。','Zero additional cost erases effort.')
l('STATES.a_motion.treatment.blocks.2.label','可以选取的片段','Optional selection, not technique lesson.')
l('STATES.a_motion.treatment.blocks.2.text','可以从已经拍好的片段中，选取画面变化清楚的部分，例如颜色扩散、明暗形成或建筑细节逐渐出现。是否保留完整过程，取决于这条视频想呈现什么。','Do not invent salt/drybrush as her technique or promise attention.')
l('STATES.a_motion.treatment.blocks.3.label','用于其他平台前，需要检查什么','Replace same-file magical portability.')
l('STATES.a_motion.treatment.blocks.3.text','以画面为主的片段可以减少语言转换工作。用于其他平台前，仍需检查画幅、时长、字幕、音乐使用范围与封面。','No platform reach guarantees.')
l('STATES.a_motion.treatment.blocks.4.label','放进作品介绍','Replace vague position.')
l('STATES.a_motion.treatment.blocks.4.text','过程片段也可以放在系列介绍或作品集旁边，帮助编辑、合作方和读者了解创作方式。','No assertion buyers reassured or series easier to maintain.')
l('STATES.a_weekly.label','尝试跨平台发布过程片段','No inference nobody has seen videos.')
l('STATES.a_weekly.detail','2023 年连续发布的翻页视频中，有几条取得较高播放量。这组内容可以作为研究样本，比较主题、编排与发布时间，再判断哪些部分值得重新使用。','Remove best achievement ever and cross-platform unseen claim.')
l('STATES.a_weekly.treatment.open','看看这组视频的数据','Observation not proof.')
l('STATES.a_weekly.treatment.blocks.0.label','这批样本中，短视频的播放中位数较高','Metric attached to comparison.')
l('STATES.a_weekly.treatment.blocks.0.text','在目前记录的 33 条视频中，时长不足两分半的视频播放中位数约为 9,975，较长视频约为 1,172，相差约 8.5 倍。这是该批样本的差异；题材、发布时间和传播条件也可能影响结果。','Specify sample and measure; do not equate views with reward or effort.')
l('STATES.a_weekly.treatment.blocks.1.label','系列编排也值得比较','Hypothesis, not causal claim.')
l('STATES.a_weekly.treatment.blocks.1.text','2023 年这组视频围绕完成的日记、编号和连续发布展开。可以把这些特点与其他视频比较；仅凭播放量，还不能确定观众是否为了下一集回来。','Avoid 钩子 and invented repeat-viewing motivation; remove humiliating 139-view contrast from headline.')
l('STATES.a_weekly.treatment.blocks.2.label','播放量还不能说明什么','Useful uncertainty.')
l('STATES.a_weekly.treatment.blocks.2.text','播放次数可能包含重复观看。把历史播放量与今天的关注数量相除，也无法推算当时有多少新观众或新增关注。若要判断这一点，需要对应时期的后台数据。','No views > followers => discovery proof.')
l('STATES.a_weekly.treatment.blocks.3.label','让作品介绍便于日后查看','No scolding not-stories title.')
l('STATES.a_weekly.treatment.blocks.3.text','如果希望日后进入主页的人也能找到，可以选择便于长期查看的发布方式，并按当前平台功能整理作品。','Avoid brittle claims about stories and curator arrival month.')
l('STATES.a_weekly.treatment.blocks.4.label','先检查一条已有视频','Small optional step.')
l('STATES.a_weekly.treatment.blocks.4.text','可以先选一条已有片段，检查画幅、字幕、音乐和文件质量，再判断是否适合用于另一个平台。','No only-reason blame or claim files definitely retained.')
l('STATES.a_borrowed.label','与其他创作者共同呈现作品','People not audience assets to borrow.')
l('STATES.a_borrowed.detail','合印 zine、共同展览或互相介绍作品，都是可能的合作方式。对象是否适合，需要看作品、双方意愿与实际联系；这份资料不代表合作已经成立。','No fastest growth claim; referenced 12-person map is unmounted.')
l('STATES.a_second.label','不同平台上的读者','Platform not language.')
l('STATES.a_second.detail','微博、小红书、B 站、Instagram 和 X 上的作品呈现，可以按各平台的内容与读者反馈分别研究。关注数量、读者语言和购买情况是不同的信息。','Avoid false Chinese/English split.')
l('STATES.a_second.treatment.open','比较不同平台能提供什么','Plain label.')
l('STATES.a_second.treatment.blocks.0.label','小红书上的现有内容','Not unsupported platform-wide popularity.')
l('STATES.a_second.treatment.blocks.0.text','可以从已经发布的街景、室内与日常题材中，比较读者对哪些内容有回应。语言、配文和选图都可作为观察条件。','No invented top content categories or nationality = genre.')
l('STATES.a_second.treatment.blocks.1.label','分别了解读者与购买条件','Remove two-room metaphor.')
l('STATES.a_second.treatment.blocks.1.text','不同平台的读者可能重叠。判断销售机会时，需要分别了解可用的购买渠道、配送范围和实际订单，不能只比较关注数量。','No assumed currencies, no shared collapse claim.')
l('STATES.a_second.treatment.blocks.2.label','视频素材的其他用途','Natural heading.')
l('STATES.a_second.treatment.blocks.2.text','已有过程视频可以作为跨平台尝试的素材。以画面为主的片段可能减少翻译工作，仍需检查发布规格与声音使用范围。','Remove unique language-free medium, unsupported follower intent.')
l('STATES.a_second.treatment.blocks.3.label','对外介绍时选哪个账号','Utility without ranking people.')
l('STATES.a_second.treatment.blocks.3.text','选择便于对方查看作品、且内容完整的账号。关注数量可以单独记录，但不必决定每一次介绍使用哪个平台。','Do not infer X audience English; respect Instagram-only outreach instruction.')
l('STATES.a_second.treatment.blocks.4.label','还需要哪些信息','Avoid internal bookkeeping story.')
l('STATES.a_second.treatment.blocks.4.text','目前不能从公开关注数确认跨平台重叠、读者语言、实际触达或购买意愿。后续有相应记录时，再补充这些判断。','Follower sum not ceiling on reach: nonfollowers may view too.')
l('STATES.a_inbound.label','逐步了解实际购买需求','Inbound attention not guaranteed purchasability.')
l('STATES.a_inbound.detail','已有关注可以帮助新产品被看见，是否购买仍需通过实际订单了解。印量可以结合试卖或预订情况来安排，避免直接用关注数量预测销量。','Remove gambling reassurance and flawed 109/follower arithmetic.')
l('STATES.l_reproduces.label','适合印制的作品文件','Print fidelity is testable, not inherent in subject.')
l('STATES.l_reproduces.detail','现有作品可以通过样品检查缩放、裁切和色彩还原，再判断适合哪些印刷产品。','No automatic reproduction suitability.')
l('STATES.l_inprint.detail','已有 zine 和出版物，可以作为作品印制效果的样本。授权使用前仍需确认图像文件与相关权利。','No quality vs production lecture; rights may differ.')
l('STATES.l_lookbook.label','可供合作方查看的授权作品集','No same-day completion promise.')
l('STATES.l_lookbook.detail','可将选定作品与少量产品排版样例放进一份 PDF，并附上联系方式和授权说明。样例用于说明用途，不代表已有商业合作。','Do not insult art director imagination; remove arbitrary 10–20 demand.')
l('STATES.l_findable.label','可被检索的作品资料','Plain purpose.')
l('STATES.l_findable.detail','可以查看相关作品目录和图库的收录要求、费用与合同。是否已经收录你的资料，需要另外确认。','No “most licensing inbound” claim or measured gap inference.')
l('STATES.l_first.detail','如果已有付费授权，可以记录使用范围、期限、费用和结算方式，供下一次报价参考。这里尚未确认相关记录。','Unknown is not absence; remove commission rates misused as license fees.')
l('STATES.l_repeat.label','再次合作与追加使用','Three jobs do not determine a market price.')
l('STATES.l_repeat.detail','持续合作可以积累更具体的报价依据。再次使用作品时，需按新增用途、范围和期限商议。','Remove pseudo pricing rules and detached 800k calendar example.')
l('STATES.l_inbound.label','品牌主动询问合作','Neutral optional outcome.')
l('STATES.l_inbound.detail','ほぼ日的插画合作系列可作为研究案例。未找到公开投稿入口，只能说明目前可确认的渠道有限，不能据此判断合作只能怎样开始。','No-door metaphor is determinism; lack of public route not proof only inbound.')
l('GOALS.0.name','画廊合作与展览','Clear goal without game.')
l('GOALS.1.name','作品传播与读者','Her audience already established.')
l('GOALS.2.name','国际图像授权','Distinguish image rights from broad licensing.')
l('GOALS.2.why.a_look','产品系列需要在不同尺寸和版式下保持画面的一致性，可以通过样例和打样来检查。','Remove 面貌铺成产品线 translation.')
l('GOALS.2.why.a_series','相关作品便于展示一个产品系列的可能性，是否采用仍取决于具体需求。','Named series not inherently easier sale than strong single image.')

def write_reports():
    inv=json.loads((OUT/'python_copy_inventory.json').read_text(encoding='utf-8'))
    parts=['# Saffron Chinese audit — engine-owned copy\n\n2026-09-10. Exact source wording is preserved below. Line numbers refer to this review snapshot. This is an editorial proposal, not a production patch.\n\nEvery `_t(en, zh)` unit in the three active content engines was read. Neutral names, quantities, currencies and already-clear labels are retained unless flagged. A retained numeric literal is **not** factual approval: numeric tables remain subject to the model/source blockers in the improvement brief. “Hold” entries provide safe draft wording but must not be shipped with the old model. English must be corrected alongside Chinese wherever the underlying claim changes.\n\nFor f-strings, `{...}` preserves the source expression; implementers must retain real interpolation rather than paste expressions into the UI.\n']
    stats={}
    for file in [F,B,R,O]:
        group=[r for r in inv if r['file']==file]
        parts.append('\n## '+file+'\n')
        for i,row in enumerate(group,1):
            exact=(file,row['line'],row['zh'])
            decision=EDITS.get(exact,EDITS.get((file,row['line'],None)))
            if file==O and row['line']!=75:
                decision=('', 'Not rendered by current Saffron. Do not spend the next release polishing unmounted etiquette copy.', 'Out of current UI')
            if decision:
                new,why,status=decision
            else:
                new=row['zh']; why='Clear label, proper name or numeric cell. Retain wording; verify factual/numeric fields under the cross-cutting checks.'; status='Retain wording'
            stats[status]=stats.get(status,0)+1
            ref=f"[{file}:{row['line']}](C:/ScottStuff/GalleryAgentAI/{file}:{row['line']})"
            parts += [f'\n### {file.split("/")[-1]} · {i:03d} · {status}\n\n{ref}\n\n**Current**\n\n'+ '\n'.join('> '+s for s in row['zh'].split('\n'))+'\n']
            if status not in ['Retain wording','Out of current UI']:
                parts.append('\n**Replace with**\n\n'+new+'\n')
            parts.append('\n**Reason:** '+why+'\n')
    (OUT/'02-Chinese-engine-copy.md').write_text('\n'.join(parts),encoding='utf-8')
    data=json.loads((OUT/'ladders_snapshot.json').read_text(encoding='utf-8'))
    rows=[]
    def walk(o,p=''):
        if isinstance(o,dict):
            if 'zh' in o and 'en' in o: rows.append((p,o['zh'])); return
            for k,v in o.items():walk(v,p+'.'+k if p else k)
        elif isinstance(o,list):
            for i,v in enumerate(o):walk(v,p+'.'+str(i))
    walk(data)
    parts=['# Saffron Chinese audit — all strategy ladder copy\n\nSource: [strategy_ladders.js](C:/ScottStuff/GalleryAgentAI/frontend/src/data/strategy_ladders.js). Exact object paths are stable locators. Every Chinese leaf was reviewed, including all expanded treatments. These prose proposals accompany a structural recommendation to replace scored ladders with evidence and optional sequences; changing labels alone does not correct the evidence rules.\n']
    for p,old in rows:
        dec=LADDER_EDITS.get(p)
        parts.append('\n## '+p+(' — Rewrite' if dec else ' — Retain')+'\n\n**Current:** '+old+'\n')
        if dec:parts.append('\n**Replace with:** '+dec[0]+'\n\n**Reason:** '+dec[1]+'\n')
    (OUT/'03-Chinese-strategy-ladders.md').write_text('\n'.join(parts),encoding='utf-8')
    (OUT/'copy_decision_summary.json').write_text(json.dumps({'engine_units':len(inv),'engine_decisions':stats,'ladder_units':len(rows),'ladder_rewrites':len(LADDER_EDITS)},indent=2),encoding='utf-8')
    print(json.dumps({'engine_units':len(inv),'engine_decisions':stats,'ladder_units':len(rows),'ladder_rewrites':len(LADDER_EDITS)}))

if __name__=='__main__':write_reports()
