// Mochi page strings — v2.mochi.* namespace only.
// Consumed via useLocalT(strings); unknown keys fall back to the global dictionary
// (cat.*, card.*, tf.*, cal.*, section.*, detail.* already exist there).
export const strings = {
  en: {
    'v2.mochi.greeting.morning':   'Good morning.',
    'v2.mochi.greeting.afternoon': 'Good afternoon.',
    'v2.mochi.greeting.evening':   'Good evening.',
    'v2.mochi.voice.found':        'Mochi found three things worth your attention today.',
    'v2.mochi.voice.quiet':        'Nothing urgent. Come back tomorrow.',
    'v2.mochi.voice.hunting':      'Mochi is out hunting…',

    'v2.mochi.focus.recheck':      'deadline passed — Mochi is re-checking',
    'v2.mochi.focus.followup':     'Follow-up',
    'v2.mochi.act.copyEmail':      'Copy email',
    'v2.mochi.act.copied':         'Drafted and copied — paste it into Instagram DM or email.',
    'v2.mochi.act.openPage':       'Open page',

    'v2.mochi.board.title':        'The Hunt Board',
    'v2.mochi.board.sub':          'Everything Mochi is tracking, in one place.',
    'v2.mochi.filter.all':         'All',
    'v2.mochi.filter.best':        'Best Moves',
    'v2.mochi.filter.open_calls':  'Open Calls',
    'v2.mochi.filter.publications':'Publications',
    'v2.mochi.filter.competitions':'Competitions',
    'v2.mochi.filter.zines':       'Zines & Print',
    'v2.mochi.filter.galleries':   'Galleries & Cafés',
    'v2.mochi.filter.watch':       'Watch List',
    'v2.mochi.view.cards':         'Cards',
    'v2.mochi.view.deadlines':     'Deadlines',

    'v2.mochi.fit.strong':         'Strong fit',
    'v2.mochi.fit.good':           'Good fit',
    'v2.mochi.fit.worth':          'Worth a look',
    'v2.mochi.fit.quiet':          'Quiet lead',
    'v2.mochi.evidence.title':     'Why Mochi thinks so',
    'v2.mochi.chip.deadline':      'deadline ✓',
    'v2.mochi.chip.contact':       'contact ✓',
    'v2.mochi.chip.link':          'link ✓',
    'v2.mochi.chip.draft':         'draft ✓',

    'v2.mochi.stale.title':        'Mochi is re-checking these {n} — they may have closed.',
    'v2.mochi.empty.board':        'Nothing here yet. Mochi will keep hunting.',
    'v2.mochi.empty.deadlines':    'No firm deadlines in the next 30 days. The leads are still there — Mochi is confirming dates.',
  },
  zh: {
    'v2.mochi.greeting.morning':   '早上好。',
    'v2.mochi.greeting.afternoon': '下午好。',
    'v2.mochi.greeting.evening':   '晚上好。',
    'v2.mochi.voice.found':        '猫饼为你找到了三件值得留意的事。',
    'v2.mochi.voice.quiet':        '今天没有要紧的事，明天再来吧。',
    'v2.mochi.voice.hunting':      '猫饼正在外面巡视……',

    'v2.mochi.focus.recheck':      '截止已过 — 猫饼正在重新核实',
    'v2.mochi.focus.followup':     '跟进',
    'v2.mochi.act.copyEmail':      '复制邮件',
    'v2.mochi.act.copied':         '草稿已复制——粘贴到 Instagram 私信或邮件即可。',
    'v2.mochi.act.openPage':       '打开页面',

    'v2.mochi.board.title':        '猫饼的猎场',
    'v2.mochi.board.sub':          '猫饼正在追踪的一切，都在这里。',
    'v2.mochi.filter.all':         '全部',
    'v2.mochi.filter.best':        '最佳行动',
    'v2.mochi.filter.open_calls':  '公开征集',
    'v2.mochi.filter.publications':'出版刊载',
    'v2.mochi.filter.competitions':'比赛奖项',
    'v2.mochi.filter.zines':       '小志印刷',
    'v2.mochi.filter.galleries':   '画廊与咖啡馆',
    'v2.mochi.filter.watch':       '观察名单',
    'v2.mochi.view.cards':         '卡片',
    'v2.mochi.view.deadlines':     '截止日期',

    'v2.mochi.fit.strong':         '非常契合',
    'v2.mochi.fit.good':           '比较契合',
    'v2.mochi.fit.worth':          '值得一看',
    'v2.mochi.fit.quiet':          '潜在线索',
    'v2.mochi.evidence.title':     '猫饼的依据',
    'v2.mochi.chip.deadline':      '截止 ✓',
    'v2.mochi.chip.contact':       '联系 ✓',
    'v2.mochi.chip.link':          '链接 ✓',
    'v2.mochi.chip.draft':         '草稿 ✓',

    'v2.mochi.stale.title':        '猫饼正在重新核实这 {n} 项——它们可能已经截止。',
    'v2.mochi.empty.board':        '这里暂时没有猎物。猫饼会继续找的。',
    'v2.mochi.empty.deadlines':    '未来30天内没有确定的截止日期。线索还在——猫饼正在核实日期。',
  },
  ja: {
    'v2.mochi.greeting.morning':   'おはようございます。',
    'v2.mochi.greeting.afternoon': 'こんにちは。',
    'v2.mochi.greeting.evening':   'こんばんは。',
    'v2.mochi.voice.found':        'モチが今日、気になるものを三つ見つけてきました。',
    'v2.mochi.voice.quiet':        '急ぎのものはありません。また明日。',
    'v2.mochi.voice.hunting':      'モチは見回りに出ています……',

    'v2.mochi.focus.recheck':      '締切超過 — モチが再確認中',
    'v2.mochi.focus.followup':     'フォローアップ',
    'v2.mochi.act.copyEmail':      'メールをコピー',
    'v2.mochi.act.copied':         '下書きをコピーしました——Instagram の DM かメールに貼り付けてください。',
    'v2.mochi.act.openPage':       'ページを開く',

    'v2.mochi.board.title':        'モチの狩り場',
    'v2.mochi.board.sub':          'モチが追いかけているものが、ここにまとまっています。',
    'v2.mochi.filter.all':         'すべて',
    'v2.mochi.filter.best':        'ベストムーブ',
    'v2.mochi.filter.open_calls':  '公募',
    'v2.mochi.filter.publications':'出版・掲載',
    'v2.mochi.filter.competitions':'コンペ・賞',
    'v2.mochi.filter.zines':       'ジン・印刷',
    'v2.mochi.filter.galleries':   'ギャラリー・カフェ',
    'v2.mochi.filter.watch':       'ウォッチリスト',
    'v2.mochi.view.cards':         'カード',
    'v2.mochi.view.deadlines':     '締め切り',

    'v2.mochi.fit.strong':         'ぴったり',
    'v2.mochi.fit.good':           '相性よし',
    'v2.mochi.fit.worth':          '一見の価値',
    'v2.mochi.fit.quiet':          '静かな候補',
    'v2.mochi.evidence.title':     'モチの根拠',
    'v2.mochi.chip.deadline':      '締切 ✓',
    'v2.mochi.chip.contact':       '連絡先 ✓',
    'v2.mochi.chip.link':          'リンク ✓',
    'v2.mochi.chip.draft':         '下書き ✓',

    'v2.mochi.stale.title':        'モチが {n} 件を再確認しています——締め切られているかもしれません。',
    'v2.mochi.empty.board':        'ここはまだ空っぽです。モチが探しつづけます。',
    'v2.mochi.empty.deadlines':    '今後30日間に確定した締切はありません。手がかりはあります——モチが日付を確認中です。',
  },
}
